### ISSUE TITLE
Add support for signInWithBrowser method

### ISSUE THREAD

**Issue by sloyless** [sehgalrishabh/okta-react-native-web#3]
Hi there! I just found this package after running into the same unique situation you did and was happy to find this package.

We're using `signInWithBrowser` with the `@okta/okta-react-native` package. At first test it looks like your package only supports normal `signIn`. Any plans to support that functionality? Or am I missing something in the documentation to handle the redirect login?

**Comment by sehgalrishabh** [comment]
Hi @sloyless, this library solely create for **react-native-web** and does not support mobile platforms.
I'll suggest you to use `Platform` API provided by `react-native` in and render platform specific Navigation or you can use [Platform specific extensions](https://reactnative.dev/docs/platform-specific-code).

> Any plans to support that functionality?

Since okta already provides support for react-native for mobile ([@okta/okta-react-native](https://github.com/okta/okta-react-native)), it's advisable to use `@okta/okta-react-native` for android/ios.

> Or am I missing something in the documentation to handle the redirect login?

In `okta-react-native-web`, `authRedirect` prop is available that can be passed in `OktaProvider`. This prop accepts a function where you can add your custom logic or redirection for login in this prop.

I will try to update and add detailed information about all the props in the Readme file as well.

Hope this helps. If you are still facing any issues please feel free to reopen.
